# This Compose file assumes there is local Dockerfile The "build: ," line below
# The Compose this image:
# docker-compose up
# To tag this image with the matlus prefix:
# docker tag rmq-matlus:youtube matlus/rmq-matlus:youtube
# To Push the image to Docker Hub:
# docker push matlus/rmq-matlus:youtube
# To pull this image from DockerHub
# docker pull matlus/rmq-matlus:youtube
version: '3'
services:
  rmq-matlus:
    image: rmq-matlus:youtube
    build: .
    ports:
      - "5672:5672"
      - "15672:15672"

# To Run the Image from Docker Hub
# docker run -p 5672:5672 -p 127.0.0.1:15672:15672 --name rmq-matlus-container -d matlus/rmq-matlus:youtube